target("container")
    set_kind("headeronly")
    add_headerfiles("include/spl/container/*.hpp")
    add_includedirs("include", {public = true})
    add_deps("concepts", "core", {public = true})
    add_packages("boost", {public = true})
target_end()

target("container-test")
    set_kind("binary")
    set_group("test")
    add_files("test/*.cpp")
    add_deps("container")
    add_packages("gtest")
    set_group("test")
target_end()