target("fetcher")
    set_kind("headeronly")
    add_headerfiles("include/spl/fetcher/*.hpp")
    add_includedirs("include", {public = true})
    add_deps("exchange-factory", "components-feeder", "candlestick", {public = true})
target_end()

target("fetcher-test")
    set_kind("binary")
    set_group("test")
    add_files("test/*.cpp")
    add_deps("fetcher")
    add_packages("gtest")
target_end()
