target("math")
    set_kind("headeronly")
    add_headerfiles("include/spl/math/*.hpp")
    add_includedirs("include", {public = true})
    add_deps("core", "types", {public = true})
target_end()

target("math-test")
    set_kind("binary")
    set_group("test")
    add_files("test/*.cpp")
    add_deps("math")
    add_packages("gtest")
    set_group("test")
target_end()