target("network")
    set_kind("headeronly")
    add_headerfiles("include/spl/network/**/*.hpp")
    add_includedirs("include", { public = true })
    add_defines("BOOST_STATIC_STRING_STANDALONE", { public = true })
    add_cxxflags("-Wno-deprecated-declarations", { public = true })
    add_cxxflags("-lc++abi", { public = true })
    add_deps("core", "meta", "result",  "concepts", "logger", { public = true })
    add_packages("boost", "openssl", "libcurl", { public = true })
target_end()

target("network-test")
    set_kind("binary")
    set_group("test")
    add_files("test/*.cpp")
    add_deps("network")
    add_packages("gtest")
target_end()
