target("logger")
    set_kind("headeronly")
    add_headerfiles("include/spl/logger/*.hpp")
    add_includedirs("include", {public = true})
    add_deps("types",  "meta",  "reflect", {public = true})
target_end()

target("logger-test")
    set_kind("binary")
    set_group("test")
    add_files("test/*.cpp")
    add_deps("logger")
    add_packages("gtest")
target_end()