target("candlestick")
    set_kind("headeronly")
    add_headerfiles("include/spl/candlestick/*.hpp")
    add_includedirs("include", {public = true})
    add_deps("protocol-feeder",  "math", {public = true})
target_end()

target("candlestick-test")
    set_kind("binary")
    set_group("test")
    add_files("test/*.cpp")
    add_deps("candlestick")
    add_packages("gtest")
target_end()
