target("components-scheduler")
    set_kind("headeronly")
    add_headerfiles("include/spl/components/scheduler/*.hpp")
    add_includedirs("include", {public = true})
    add_deps("meta", "result", "types", {public = true})
target_end()

target("components-scheduler-test")
    set_kind("binary")
    set_group("test")
    add_files("test/*.cpp")
    add_deps("components-scheduler")
    add_packages("gtest")
target_end()