target("codec-json")
    set_kind("headeronly")
    add_headerfiles("include/spl/codec/json/*.hpp")
    add_includedirs("include", {public = true})
    add_deps("concepts", "meta", "reflect", "types",  "result",  "logger", {public = true})
    add_packages("daw_json_link", {public = true})
target_end()

target("codec-json-test")
    set_kind("binary")
    set_group("test")
    add_files("test/*.cpp")
    add_deps("codec-json")
    add_packages("gtest")
    set_group("test")
    add_cxflags("-Wno-return-stack-address")
target_end()
