target("metrics")
    set_kind("headeronly")
    add_headerfiles("include/spl/metrics/*.hpp")
    add_includedirs("include", { public = true })
    add_deps("result", "types", "container", { public = true })
target_end()

target("metrics-test")
    set_kind("binary")
    set_group("test")
    add_files("test/*.cpp")
    add_deps("metrics", "protocol-feeder")
    add_packages("gtest")
    set_group("test")
target_end()

target("metrics-benchmark")
    set_kind("binary")
    add_headerfiles("benchmark/*.hpp")
    add_files("benchmark/multimeter_benchmark.cpp")
    add_includedirs("benchmark", { public = true })
    add_deps("metrics", "protocol-feeder", { public = true })
    add_packages("benchmark")
target_end()
