target("metrics")
    set_kind("headeronly")
    add_headerfiles("include/spl/metrics/*.hpp")
    add_includedirs("include", { public = true })
    add_deps("result", "types", "container", { public = true })
target_end()

target("metrics-test")
    set_kind("binary")
    set_group("test")
    add_files("test/*.cpp")
    add_deps("metrics", "protocol-feeder")
    add_packages("gtest")
    set_group("test")
target_end()
